<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<!-- saved from url=(0225)http://64.4.26.250/cgi-bin/getmsg?curmbox=F000000001&a=2a9951dc46aad0a28d550be99af68238&msg=MSG1071547433.17&start=1098535&len=3248&mimepart=3&disk=64.4.26.74_d137&login=hernanseghetti&domain=hotmail%2ecom&_lang=ES&country=AR -->
<HTML><HEAD>
<META content="text/html; charset=iso-8859-1" http-equiv=Content-Type>
<META content="MSHTML 5.00.2614.3500" name=GENERATOR></HEAD>
<BODY><XMP>#include <time.h>
#include <stdio.h>
#include <dos.h>
#include <iostream.h>
#include <conio.h>

void main()
{
textcolor(2);
clrscr();
cout<<"presiona algo";getch();

sound (400);delay (300);nosound();delay (50);
sound (400);delay (300);nosound();delay (20);
sound (450);delay (400);//nosound();delay (20);
sound (400);delay (400);//nosound();delay (20);
sound (530);delay (400);//nosound();delay (20);
sound (500);delay (400);//nosound();

sound (400);delay (300);nosound();delay (50);
sound (400);delay (300);nosound();delay (20);
sound (450);delay (400);//nosound();//delay (20);
sound (400);delay (400);//nosound();//delay (20);
sound (600);delay (400);//nosound();//delay (20);
sound (530);delay (400);//nosound();delay (20);

sound (400);delay (300);nosound();delay (20);
sound (400);delay (300);nosound();delay (20);
sound (670);delay (550);//nosound();delay (50);
sound (530);delay (400);nosound();//delay (20);

sound (500);delay (400);nosound();delay (50);
sound (500);delay (500);nosound();delay (20);
sound (500);delay (400);nosound();delay (20);
sound (450);delay (800);nosound();delay (20);

sound (700);delay (400);nosound();delay (50);
sound (700);delay (500);nosound();delay (20);
sound (670);delay (400);nosound();delay (20);
sound (530);delay (700);nosound();delay (20);

sound (600);delay (700);nosound();delay (50);
sound (530);delay (1100);


getch();
}







</XMP></BODY></HTML>
